### ISSUE TITLE
Populate a To-Do

### ISSUE THREAD

**Issue by bayoumi17m** [CornellDataScience/RL-Halite#1]
Make a list of things to do

**Comment by TheButlah** [comment]
yeet

**Comment by TheButlah** [comment]
@daggertye we don't have to do a text based sprint if we use the project board

**Comment by daggertye** [comment]
Ah I realize taht now

**Comment by TheButlah** [comment]
Bish we didn't make the TODO yet so we can't close the issue

**Comment by bayoumi17m** [comment]
We have started our TODO, so I am closing this. We just need to decide how to go about adding smaller portions of the project to the board (manually or through issues)
